### PR TITLE
sync fork

### PR DESCRIPTION
**Pull request by thx123**

### CODE REVIEW

**Comment by thx123** [comment]
Sorry for this accidental merge request (already closed). It was meant to be a sync in my fork.

**Comment by hexdae** [comment]
No problem, if any of these changes are needed in the main branch let me know and we can integrate it. I'm planning to clean up bzlmod support and make it a first class citizen soon

**Comment by thx123** [comment]
Hi @hexdae,

Thanks for your reply! Here are a few changes that I made in order to reuse your repo, some of which shown in [this diff](https://github.com/thx123/bazel-arm-none-eabi/compare/4f3f31d629259e65e98b3aa7d8cb8c916cf7e03c..5536872dd01c746bbb59f3021c5f550dd1cdd225]:

## in `MODULE.bazel`:

Renaming the extension name to be different from the module name (just to avoid possible confusions)
```
- arm_none_eabi = use_extension("@arm_none_eabi//:extensions.bzl", "arm_none_eabi")
- arm_none_eabi.toolchain(version = "9.2.1")
+ arm_none_eabi_extension = use_extension("@arm_none_eabi//:extensions.bzl", "arm_none_eabi_extension")
+ arm_none_eabi_extension.toolchain(version = "9.2.1")
```

// Adding platform module so that this module won't break when reused inside another module
```
# DEV ONLY (not needed for release)
bazel_dep(name = "aspect_bazel_lib", version = "2.0.0", dev_dependency = True)
bazel_dep(name = "bazel_skylib", version = "1.5.0", dev_dependency = True)
+ # This is needed by arm_none_eabi_extensions, if called outside this repo.
+ bazel_dep(name = "platforms", version = "0.0.8", dev_dependency = False)
```

// Inside `extensions.bzl`, add a condition to skip http repo creation; otherwise the toolchain repo creation code would be invoked multiple times (once from this module, another time from the module that depeds on this module), causing Bazel build to fail:

```
def _arm_none_eabi_impl(ctx):
    for mod in ctx.modules:
      + # Avoiding duplicate repo generations from outside the module
      + if mod.name != "arm_none_eabi":
      +     continue
        for attr in mod.tags.toolchain:
            arm_none_eabi_deps(attr.version)
```
There may be more elegant solutions but this is a pratical "hack" that I could find to avoid the failure.

Thanks!

**Comment by hexdae** [comment]
Thank you for adding these @thx123, I addressed them in #27

**Pull request closed without merging**
